#!/usr/bin/env bash
#configure nginx to listen on port 80 but the service is not running
sed -i 's/8080 default/80 default/' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
