#!/usr/bin/env bash
# SSH client configuration

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPAuthrntication yes
	GSSAPIDelegateCrendentials no
